### ISSUE TITLE
Detected on avast

### ISSUE THREAD

**Issue by Dan777ok** [Malopieds/InnerTune#135]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

Hello I had this install but avast keep detected it as virus(trojan)? You can check it on virustotal idk if it's a false alert but maybe you can clear this up thanks you @Malopieds

**Comment by Malopieds** [comment]
Uploading it on virustotal seems fine

**Comment by Dan777ok** [comment]
https://www.virustotal.com/gui/file/5c7eca5c3e145432b7a7d16932aa41975afb0282be5626740fc12427e0ad2b77/summary
Here you go it is detected as Evo gen @Malopieds

**Comment by Malopieds** [comment]
https://www.virustotal.com/gui/file/e0eede0d720c946a5ee331f0273a0300506f1ae320be37e5b821965f84bb69da
On last build

**Comment by Dan777ok** [comment]
Ohh okay so it's a false alert. 
Do you know why it was detected as virus the older build?
Thanks you @Malopieds

**Comment by Malopieds** [comment]
> Do you know why it was detected as virus the older build?

With which one do you tried? At this point I don't really care about what antivirus have to say, I prefer know what I'm using or check the code directly...

**Comment by Dan777ok** [comment]
I have this install v0.5.7-rc1
But it's okay if you know you keeping your app safe. @Malopieds 
I was just letting you know as a user.
I will update to the latest version 

Thanks you tho

**Comment by slavache54** [comment]
hi! from the answers in the discussion, it's not entirely clear if there are viruses in the build? v0.5.7-rc2 detects viruses.
![uuuu](https://github.com/Malopieds/InnerTune/assets/114473503/14434f7f-f87c-4ef3-a13c-15d52955b34a)

**Comment by Malopieds** [comment]
> hi! from the answers in the discussion, it's not entirely clear if there are viruses in the build? v0.5.7-rc2 detects viruses.

Avast is a false positive mostly, (see [this](https://forum.avast.com/index.php?topic=323096.0))

with secure seems to be showing the same virus than avast. And cynet I have no clue they're not even saying what they think it is.
In addition, when I ran it 4 days ago everything was green... So yeah I mean I don't believe in antivirus, you have the right not to trust me, if so look at the code or don't install the app. It's as simple as this.

**Comment by Drmanhattan84** [comment]
You cant release builds without proper testing. I am well aware that some Anti virus software /services create more trouble than the regulate. But rushing to push new versions in your pace only to update the original version of InnerTune with minor features, well that raises a lot of red flags. The Evo gen detection is valid as you can verify by looking at the ram utilization.

**Comment by Dan777ok** [comment]
@Drmanhattan84 So there is a virus on the app?
Is it that harmful?

Thanks

**Comment by Drmanhattan84** [comment]
If you know how to verify apk with termux,you will be able to detect iregular attributes from the console

**Comment by Malopieds** [comment]
> But rushing to push new versions in your pace only to update the original version of InnerTune with minor features, well that raises a lot of red flags

I get that you could see this way, but what do you want me to do? Stop releasing new versions? To the pace that this is going, I'd like to have a mature project but that means a lot of changing (that can break things) so I prefer releasing more so that more people can test.

> The Evo gen detection is valid as you can verify by looking at the ram utilization

I don't see that, how have you experienced that?

> If you know how to verify apk with termux,you will be able to detect iregular attributes from the console

That is **clearly** not the point of termux, but please, go on and explain how you do this then?

Once again this is an open source, you can verify every commits (as you should) if you don't trust me. And ultimately raise a real issue without throwing allegation that are not backed up with a minimal proof.

[This](https://www.virustotal.com/gui/file/a4b7f3762f6130e6b9026c10db8130c69cb658f388e9c0a36fa2a0d7e314ca81?nocache=1) is latest debug build
And [this](https://www.virustotal.com/gui/file/87fc3ceece376986c9cf76d178de25c9a1fd12c88292159982a2858c95241e1e?nocache=1) is a build I just made.

In addition I will send the apk to avast false positive detection, what the original creator of the app has done, this way there will be no doubt.

**Comment by vedxp** [comment]
@Malopieds seems they've removed the false-positive.

Here's the reply I got upon submission:
```
In relation to submission 365603.

Upon further analysis and investigation we have verified your submission and, as such, the detection(s) for the following file(s) will be removed from our products:

    File name: app.apk
    MD5: CD8BC5FF18DE888916C8743A0F4B3529
    SHA256: 1FE3A2CE2EDEB899DAC979BB77C76B2AA565584DFA9694DDFE05D34982488612
```

- Scan result of `v0.5.8`:
https://www.virustotal.com/gui/file/156acc5bd4e8d96bdda595e8de77c9d6e90e87cc9a030444bd93872c0c26812e/summary
