### ISSUE TITLE
Play audio over other apps

### ISSUE THREAD

**Issue by RAiNYRENJi** [Malopieds/InnerTune#225]
### Checklist

- [X] I've checked that there is no other issue about this feature request.
- [X] This issue contains only one feature request.
- [X] The title of this issue accurately describes the feature request.

### Feature description

A feature where when turned on, audio playback doesn't get interrupted when another audio from a webpage/app also plays.

### Why do you want this feature?

When scrolling through Twitter/Instagram/Pinterest or a webpage, my music gets interrupted from the other app's audio.

**Comment by zettaexa** [comment]
good request but i do think that its the apps themselves that can stop audio playing rather than innertune, for example twitter stops the audio playing from any app when you put on a video and discord lets music in when you are playing in a video, a workaround will be good but i think it will take a lot to implement

**Comment by Malopieds** [comment]
Yep that's not possible as of my scope of development.
