### ISSUE TITLE
In version 0.5.9 searchbar, header and bottom toolbar background are too bright grey in black theme

### ISSUE THREAD

**Issue by Username1-a** [Malopieds/InnerTune#315]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/Malopieds/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Looks like there's some visual inconsistency in latest version - searchbar, header and bottom toolbar background color are too bright grey compared to the rest of the app in black theme (In previous versions it looked fine (maybe would be neat to have it even darker than that))

### Expected behavior

Those UI components should be darker in black theme for more visual consistency

### Actual behavior

_

### Screenshots/Screen recordings

Comparison to the previous version 0.5.8:

![Screenshot_20240815-002732_Evolution X Launcher](https://github.com/user-attachments/assets/66d8a4ef-676e-42dd-8b8e-1f566f6f6a97)
![Screenshot_20240814-234949_Evolution X Launcher](https://github.com/user-attachments/assets/4bc8ba66-9de7-446d-9b38-c5f2562936ae)

### Logs

_

### InnerTune version

0.5.9

### Android version

Android 13 QPR3

### Additional information

Just in case, same bug is in latest version 0.5.6 of the regular Inner Tune

**Comment by Malopieds** [comment]
Yes that's an update from material design specs.
[Here](https://m3.material.io/components/search/specs#5bf33d9b-6108-4d16-bc75-7047d0704336) are [some](https://m3.material.io/components/navigation-bar/specs#1d62ff86-f860-4400-a681-5a856cdbca54) links. So I won't change that if the specs are not changed.

**Comment by Username1-a** [comment]
At least try to make it consistent for black theme, what's the point if some elements are now just light grey and sticking out like a sore thumb

**Comment by mostafaalagamy** [comment]
> Yes that's an update from material design specs.
> [Here](https://m3.material.io/components/search/specs#5bf33d9b-6108-4d16-bc75-7047d0704336) are [some](https://m3.material.io/components/navigation-bar/specs#1d62ff86-f860-4400-a681-5a856cdbca54) links. So I won't change that if the specs are not changed.

The problem isn't with the search bar or navigation bar itself; the issue lies in not fully adhering to Google's color rules. The colors of the search and navigation bars have been changed, but the background color and the rest of the application's colors haven't been adjusted to smoothly with each other.

Example for clarification.


![Screenshot_2024-08-19-09-10-22-295_com.android.chrome-edit.jpg](https://github.com/user-attachments/assets/68ac1b42-b149-47cf-b68f-feeef69ec250)

![Screenshot_2024-08-19-09-01-03-357_com.android.chrome-edit.jpg](https://github.com/user-attachments/assets/28f036f8-3554-4697-a135-ff8ea9145531)

**Comment by mostafaalagamy** [comment]
> but the background color 

Zion , add it now, merge it.
