### ISSUE TITLE
Mini player doesn't show what is current playing or shows wrong thing

### ISSUE THREAD

**Issue by PsychoAsylum** [Malopieds/InnerTune#4]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Go to Artists
2. Select one and go to song section
3. Select song

### Expected behavior

It should show songs name and artist

### Actual behavior

It is showing blank space or different title

### Screenshots/Screen recordings

![Screenshot_20240322_184115_com zionhuang music](https://github.com/Malopieds/InnerTune/assets/72300906/a851acaf-dfe2-4c51-a077-e15754f5c29e)

### Logs

I dont have logs

### InnerTune version

0.5.5

### Android version

Android 10

**Comment by Malopieds** [comment]
Hi, I also have encountered this issue while using the app. For now I don't have a fix since it happens randomly, one way to "fix" it is to open the player itself and when dragging down the player, the mini player will be updated to the right song/artist.
I will try some fixes and keep this issue updated.
