### ISSUE TITLE
Moving tracks bug

### ISSUE THREAD

**Issue by Lorestan00** [Malopieds/InnerTune#91]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

In a playlist
Drag a track to reorder
Moving it up 

### Expected behavior

You should be able to see the track move with the motion of your finger 

### Actual behavior

The track keeps flickering rather than moving up the track list in line with the motion of your finger

### Screenshots/Screen recordings

https://github.com/Malopieds/InnerTune/assets/81394097/69fc2e07-4409-45a5-9932-f300c431c974

### Logs

Na

### InnerTune version

0.5.6

### Android version

Android 14

**Comment by mikooomich** [comment]
Forgive me for possibly being ignorant, but what did that commit change exactly? Git sucks with compose and I'm having a hard time following along with what you changed. The code changes should be minimal to fix the reorder issue, instead of duplicating large parts of the code.

(see https://github.com/mikooomich/OuterTune/commit/9ee41a11c096df79c01a3a6ee4740e867b5e67e5 , there is possibly a bug with playlist indexes that breaks reorder that *may* only pertain to my repo https://github.com/mikooomich/OuterTune/commit/7a38a56e1bf74b1f7e87c6603c5b0cab13292896)

**Comment by Malopieds** [comment]
> what did that commit change exactly?

Mostly if cases but yeah with that indentation git is having a hard time following what's happening. That was just the way playlist were sorted before by date, but there was no really way of discerning in a unique way, so I added it.
